### ISSUE TITLE
meet requirement of Mongodb 3.6 {explain: true}

### ISSUE THREAD

**Issue by raza2022** [sakulstra/meteor-aggregate#2]
@sakulstra
have that package support breaking changes for 3.6 for example in aggregation there is `cursor` is mandatory if `explain` not supplied https://stackoverflow.com/questions/48680535/mongodb-error-the-cursor-option-is-required-except-for-aggregate-with-the-e
I used both meteorhacks and your packages but result is same can you give some hint please
Thanks for great work :+1:

**Comment by sakulstra** [comment]
@raza2022 I think this is not related at all to this repo. As i get it you're using mongoose... which isn't possible with meteor, is it?
Anyhow the first stackoverflow answer seems right.

**Comment by raza2022** [comment]
yes it's related to this repo. the stackoverflow question is not mine and just for reference. there should be option for explain true to pass in aggregation to meet requirement of 3.6. anyway I got it worked by using the raw collection though it's looks like some hack but worked for me :+1: 
Thanks
