### ISSUE TITLE
error with aggregate with mongodb 3.6

### ISSUE THREAD

**Issue by phanchanra** [sakulstra/meteor-aggregate#4]
Hello, before I used meteor package ''meteorhacks:aggregate" it work only mongodb 3.4. When I change mongo 3.6 with your package "sakulstra:aggregate" it get error something like that `Exception while invoking method 'school.dashboardChart' MongoError: The 'cursor' option is required, except for aggregate with the explain argument` I do not  know what problem, My app meteor version '1.4.2.2' base mongodb 3.4, Please help

**Comment by DiogoAngelim** [comment]
update meteor to the most recent version with meteor update

**Comment by phanchanra** [comment]
When I update I do not know error package or project struckure 1.4.2.2  to 
 1.7?

**Comment by sonlexqt** [comment]
I'm having the same issue these days in my app (using mlab mongo database).
@digelim are your sure updating meteor to the latest version solve the problem ?

**Comment by DiogoAngelim** [comment]
Yes @sonlexqt I just updated my app and aggregate is working now. I would make a copy of the project before updating though, to avoid dependency issues, etc.

**Comment by sonlexqt** [comment]
Thanks @digelim, in my case I didn't have to upgrade the Meteor version.
@phanchanra here's what I did:
```
const rawCollection = MyCollection.rawCollection();
const pipeline = [{
        $match: {
          ...
        },
      }, {
        $group: {
          _id: '$userId',
          count: {
            $sum: 1,
          },
        },
      }, {
        $match: {
          count: {
            $gte: 1,
          },
        },
      }];
      const result = Promise.await(rawCollection.aggregate(pipeline).toArray());
```
Source: https://github.com/meteor/meteor/issues/9936#issuecomment-394514613

**Comment by sakulstra** [comment]
sorry fellow developers, i didn't really monitor the issues here, but im glad you got it resolved.

@sonlexqt actually I think your solution is easier to read/follow than the one implemented in https://github.com/sakulstra/meteor-aggregate/blob/master/index.js#L14 ... not sure if it's worth changing the implementation though - feel free to open a pr ;)
